---
title: "Joining Tables"
author: "Sanghoon Lee"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  xaringan::moon_reader:
    css: [default, c407_slides.css]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment=NA, fig.asp = 0.56, out.width='70%', dpi = 300, fig.align = 'center')
options(tibble.print_max = Inf)
library(kableExtra)
```

inner_join()

left_join()

right_join()

full_join()

---

```{r}
library(tidyverse)
```

.pull-left[
```{r}
band_members
```
]

.pull-right[
```{r}
band_instruments
```
]

---

.pull-left-1[
.small[
```{r}
band_members
```
```{r}
band_instruments
```
]
]

.pull-right-2[
.tiny[
```{r}
band_members %>% 
  inner_join(band_instruments, by="name")
```
```{r}
band_members %>% 
  left_join(band_instruments, by="name")
```
]]

---

.pull-left-1[
.tiny[
```{r}
band_members
```
```{r}
band_instruments
```
]
]

.pull-right-2[
.tiny[
```{r}
band_members %>% 
  right_join(band_instruments, by="name")
```
```{r}
band_members %>% 
  full_join(band_instruments, by="name")
```
]]

---

.pull-left-1[
.small[
```{r}
band_members
```
```{r}
band_instruments2
```
]]

--

.pull-right-2[
.tiny[
```{r}
band_members %>% 
  inner_join(band_instruments2, by=c("name"="artist"))
```
```{r}
band_members %>% 
  left_join(band_instruments2, by=c("name"="artist"))
```
]]

