---
title: "Spatial Join - ALR"
author: "Sanghoon Lee"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  xaringan::moon_reader:
    css: [default, c407_slides.css]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment=NA, fig.asp = 0.56, out.width='70%', dpi = 300, fig.align = 'center')
options(tibble.print_max = Inf)
library(kableExtra)
set.seed(0)
```

```{r}
library(sf)
library(tidyverse)
```

---

### ALR

Google "ALR shapefile"

Choose ["Maps and GIS - ALC"](https://www.alc.gov.bc.ca/alc/content/alr-maps/maps-and-gis)

Click "ALR Geographic Information Systems Data"

Click "ALR Polygons" to download alr_polygons.zip

Unzip the file to C407/Data folder.

---

```{r}
alr <- st_read("Data/alr_polygons/ALR_Polygons.shp")
```

---

```{r}
alr %>% head()
```

---

```{r}
alr <- alr %>% select(STATUS)
alr %>% head()
```
  
---

```{r}
ggplot() + geom_sf(data=alr, fill="green") 
```

---

### BCA

```{r}
bca <- read_rds("Data/bca_sm.rds") %>% 
  sample_frac(0.01) %>% 
  select(aa_id, roll_num, lon, lat)
```

```{r}
bca %>% head()
```

---

```{r}
bca_sf <- bca %>% st_as_sf(coords=c("lon", "lat"), crs=4326)
```

```{r}
bca_sf %>% head()
```

---

```{r}
ggplot() + geom_sf(data=bca_sf, alpha=0.1)
```

---

### Spatial Join

```{r}
alr <- alr %>% st_transform(crs= st_crs(bca_sf))
```

```{r}
bca_sf <- bca_sf %>% st_join(alr)
```

---

```{r}
bca_sf %>% head()
```

---

```{r}
ggplot() + geom_sf(data=alr) + 
  geom_sf(aes(color=STATUS), data=bca_sf) + 
  coord_sf(xlim = c(-123.3, -122.46), ylim= c(49, 49.4))
```

---

```{r}
bca_z <- bca_sf %>% st_drop_geometry()
```

.small[
```{r}
bca_z %>% head()
```
]

---

```{r}
bca_z %>% count(STATUS)
```

